trigger:
- main  # or your default branch

pool:
  Name: 'Default'

steps:
- task: NuGetCommand@2
  inputs:
    restoreSolution: 'Software-Quality-and-Testing-project/SoftwareQuality.sln'
    feedsToUse: 'select'
    vstsFeed: ''
    externalFeedUrl: 'https://api.nuget.org/v3/index.json'
  displayName: 'Add NuGet source'

- script: |
    dotnet nuget locals all --clear  # Clear NuGet cache
  displayName: 'Clear NuGet cache'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'Software-Quality-and-Testing-project/SoftwareQuality.sln'
  displayName: 'Restore dependencies'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Software-Quality-and-Testing-project/SoftwareQuality.sln'
  displayName: 'Build project'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Software-Quality-and-Testing-project/InsuranceServiceTests/InsuranceServiceTests.csproj'
    arguments: '--configuration Release --logger "trx"'
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TestResults/**/*.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish test results'
