trigger:
  branches:
    include:
      - main
      
pool:
  name: 'Default'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- checkout: self

- task: DotNetCoreCLI@2
  displayName: 'Restore .NET dependencies'
  inputs:
    command: 'restore'
    projects: '**/ClassLibrary1.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build .NET solution'
  inputs:
    command: 'build'
    projects: '**/ClassLibrary1.sln'

- task: DotNetCoreCLI@2
  displayName: 'Run NUnit tests'
  inputs:
    command: 'test'
    projects: '**/ClassLibrary1.sln'
    arguments: '--logger trx'  # Optional: Customize the test logger (e.g., .trx format)

