trigger:
- main  # or your branch

pool:
  name: Default  # using your private agent

steps:
- checkout: self  # checkout your code

- script: dotnet --list-sdks
  displayName: 'List installed .NET SDKs'

- script: dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
  displayName: 'Add public NuGet source'

# Step 1: Move into the project folder where your .csproj or .sln file is
- script: |
    cd Software-Quality-and-Testing-project  # Change to the project folder
    dotnet restore  # Restore dependencies
  displayName: 'Restore dependencies'

# Step 2: Build your project
- script: |
    cd Software-Quality-and-Testing-project  # Ensure you're in the correct folder
    dotnet build  # Build your project
  displayName: 'Build project'

# Step 3: Run tests
- script: |
    cd Software-Quality-and-Testing-project  # Ensure you're in the correct folder
    dotnet test --configuration Release --logger "trx"
  displayName: 'Run tests'

# Step 4: Publish the test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'  # Use VSTest for .trx files
    testResultsFiles: '**/TestResults/*.trx'
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results'
