trigger:
  branches:
    include:
      - main  # Trigger build on the main branch, adjust as needed

# Using the default agent pool (no need to specify pool explicitly if you want to use default)
# Azure DevOps will automatically select the default agent pool.

steps:
# Step 1: Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Use .NET 6 (or any other appropriate LTS version)

# Step 2: Install Node.js (required for Angular)
- task: UseNode@1
  inputs:
    versionSpec: '16.x'  # Install a suitable Node.js version (adjust based on your project)
    addToPath: true  # Ensure Node.js is available in the PATH

# Step 3: Install Angular dependencies
- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'Install Angular dependencies'

# Step 4: Build Angular project
- script: |
    ng build --prod
  displayName: 'Build Angular project'

# Step 5: Restore .NET dependencies
- task: DotNetCoreCLI@2
  displayName: 'Restore .NET dependencies'
  inputs:
    command: 'restore'
    projects: '**/ClassLibrary1.sln'  # Adjust to your actual solution file path

# Step 6: Build .NET solution
- task: DotNetCoreCLI@2
  displayName: 'Build .NET solution'
  inputs:
    command: 'build'
    projects: '**/ClassLibrary1.sln'  # Adjust to your actual solution file path

# Step 7: Run .NET tests
- task: DotNetCoreCLI@2
  displayName: 'Run .NET tests'
  inputs:
    command: 'test'
    projects: '**/ClassLibrary1.sln'  # Adjust to your actual solution file path
