trigger:
  branches:
    include:
      - main  # Trigger build on the main branch (adjust as needed)

pool:
  name: 'Default'  # This explicitly uses the default agent pool

steps:
# Step 1: Install .NET SDK (adjust version as needed)
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Use .NET 6 (or another version you're targeting)

# Step 2: Restore .NET dependencies
- task: DotNetCoreCLI@2
  displayName: 'Restore .NET dependencies'
  inputs:
    command: 'restore'
    projects: '**/ClassLibrary1.sln'  # Adjust to your actual solution file path

# Step 3: Build .NET solution
- task: DotNetCoreCLI@2
  displayName: 'Build .NET solution'
  inputs:
    command: 'build'
    projects: '**/ClassLibrary1.sln'  # Adjust to your actual solution file path

# Step 4: Run NUnit tests
- task: DotNetCoreCLI@2
  displayName: 'Run NUnit tests'
  inputs:
    command: 'test'
    projects: '**/ClassLibrary1.sln'  # Adjust to your actual solution file path
    arguments: '--filter "TestCategory!=Integration" --logger trx'  # Optional: Customize the test filter and logger format

# Optional: Publish test results (if needed)
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TestResults/**/*.xml'
    testRunTitle: 'NUnit Tests Results'
    mergeTestResults: true
    failTaskOnFailedTests: true
